// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg16ZG8SGqJTELwnaZcj8-IsgHBap2mP4',
    appId: '1:940518039240:web:01617bb7c3007c16ebcffd',
    messagingSenderId: '940518039240',
    projectId: 'kank-4bbbc',
    authDomain: 'kank-4bbbc.firebaseapp.com',
    storageBucket: 'kank-4bbbc.appspot.com',
    measurementId: 'G-DESJP2FBTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAr7aPW6-7qQFA-GU6uQxyTsg6aKQGmzo',
    appId: '1:940518039240:android:ad62f43bbfd5db70ebcffd',
    messagingSenderId: '940518039240',
    projectId: 'kank-4bbbc',
    storageBucket: 'kank-4bbbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tBBPQCaE-qv3H1ITtuAMfNNPkzernFg',
    appId: '1:940518039240:ios:b8d87373bd20ebbbebcffd',
    messagingSenderId: '940518039240',
    projectId: 'kank-4bbbc',
    storageBucket: 'kank-4bbbc.appspot.com',
    iosBundleId: 'com.example.kankUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8tBBPQCaE-qv3H1ITtuAMfNNPkzernFg',
    appId: '1:940518039240:ios:b8d87373bd20ebbbebcffd',
    messagingSenderId: '940518039240',
    projectId: 'kank-4bbbc',
    storageBucket: 'kank-4bbbc.appspot.com',
    iosBundleId: 'com.example.kankUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZywjLr6lbZCc0-pNVpwKvgJx9iLWUN4U',
    appId: '1:940518039240:web:90105117b14137d4ebcffd',
    messagingSenderId: '940518039240',
    projectId: 'kank-4bbbc',
    authDomain: 'kank-4bbbc.firebaseapp.com',
    storageBucket: 'kank-4bbbc.appspot.com',
    measurementId: 'G-VWH4HB6F4M',
  );
}
